#Requires -Module Pester

# Guards against accidentally committing AI/tool self-attribution into
# tracked repository files (see SECURITY.md-adjacent project convention:
# this repo's artifacts must read as normal project communication).
# Scans the current working tree's git-tracked files only -- never git
# history, since rewriting past commits/comments is a separate, explicit
# decision, not something a test should force.
#
# Run with: Invoke-Pester -Path .\Tests\NoAIAttribution.Tests.ps1

BeforeAll {
    $repoRoot = Join-Path $PSScriptRoot ".."
    $bannedPatterns = @(
        'Generated by Claude Code',
        '_Generated by \[Claude Code\]',
        'Co-Authored-By:\s*Claude'
    )
}

Describe "No AI/tool attribution in tracked files" {
    It "contains none of the banned attribution strings in any git-tracked file" {
        Push-Location $repoRoot
        try {
            $trackedFiles = git ls-files
        } finally {
            Pop-Location
        }

        $hits = @()
        foreach ($relPath in $trackedFiles) {
            # This test file itself necessarily contains the banned strings
            # as literal pattern text -- exclude it from the scan.
            if ($relPath -eq "Tests/NoAIAttribution.Tests.ps1") { continue }
            $fullPath = Join-Path $repoRoot $relPath
            if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) { continue }
            $bytes = [System.IO.File]::ReadAllBytes($fullPath)
            # Skip anything that isn't plausibly text (binary asset) -- a null byte
            # in the first 8KB is a reliable enough signal without a full charset check.
            $sampleLength = [Math]::Min(8192, $bytes.Length)
            if ($bytes[0..($sampleLength - 1)] -contains 0) { continue }

            $content = Get-Content -LiteralPath $fullPath -Raw -ErrorAction SilentlyContinue
            if (-not $content) { continue }

            foreach ($pattern in $bannedPatterns) {
                if ($content -match $pattern) {
                    $hits += "$relPath -- matched pattern: $pattern"
                }
            }
        }

        $hits | Should -BeNullOrEmpty -Because "tracked files must not contain AI/tool self-attribution ($($hits -join '; '))"
    }
}
